### ISSUE TITLE
Wrapped widget not resizing correctly when increasing textstyle fontSize.

### ISSUE THREAD

**Issue by xenoliss** [asjqkkkk/markdown_widget#20] opened 2020-05-11 11:26 UTC
**Describe the bug**
When using the example 'hightlight code' given in the ReadMe, increasing the fontSize property through the textStyle argument of preConfig cause the code being clipped after several lines.

**To Reproduce**
1. Start form the example 'hightlight code'
2. Set testStyleProperty as TextStyle(fontSize: 18)
3. Write about ten lines of code
4. Notice the outputed code in the widget is getting clipped at the bottom

**Expected behavior**
The outputed code should not be clipped

**Comment by asjqkkkk** [comment] 2020-05-11 14:22
what's your flutter version?

I'm using v1.16.2, and it seems to be ok

![image](https://user-images.githubusercontent.com/30992818/81572455-ce7f7c80-93d5-11ea-9828-23db0c1c8244.png)

**Comment by BaptisteOue** [comment] 2020-05-11 15:53
I'm using Flutter 1.17.0 on beta channel (for web dev).

See the code below:
```Dart
class ExampleWidget extends StatefulWidget {
  @override
  _ExampleWidgetState createState() => _ExampleWidgetState();
}

class _ExampleWidgetState extends State<ExampleWidget> {
  String code = '';

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        LimitedBox(
          maxHeight: 100,
          child: SingleChildScrollView(
            child: TextField(
              decoration: InputDecoration(
                hintText: 'Paste your code here...',
                hintStyle: TextStyle(
                  color: Colors.grey,
                  fontSize: 18,
                ),
                border: InputBorder.none,
              ),
              style: TextStyle(
                fontSize: 18,
                color: Colors.white,
              ),
              keyboardType: TextInputType.multiline,
              maxLines: null,
              onChanged: (value) {
                setState(() {
                  code = "```\n$value\n```";
                });
              },
            ),
          ),
        ),
        Container(
          height: 300,
          child: MarkdownWidget(
            childMargin: EdgeInsets.only(top: 13),
            data: code,
            styleConfig: StyleConfig(
              preConfig: PreConfig(
                textStyle: TextStyle(fontSize: 18),
                language: 'java',
                theme: theme.a11yLightTheme,
              ),
            ),
          ),
        ),
      ],
    );
  }
}
```

After writing some lines in the textfield, the markdown widget does not scroll enough to show the last lines. Maybe this is an expected behavior ?

**Comment by asjqkkkk** [comment] 2020-05-11 16:15
![2020-05-12 00-12-39 2020-05-12 00_13_12](https://user-images.githubusercontent.com/30992818/81584533-6fc1ff00-93e5-11ea-8403-494781025d56.gif)

if you can provide some screenshot or gif, maybe the problem will be more clear

this issue looks like flutter's issue

**Comment by BaptisteOue** [comment] 2020-05-11 16:52
What I meant is that if you now remove the textStyle property you'll find the MarkdownWidget does not behave exactly identically: as long as it can expands you'll be abble to see the last line without having to press enter or to scroll.

But when you change the fontSize (like 18)  even when the widget can still expand vertically, the last line will be clipped (after several lines) unless you press enter / scroll.

After all that's maybe not that problematic and I can close this issue if you think it's a normal behavior.

**Comment by asjqkkkk** [comment] 2020-05-12 01:14
`PreWidget` is wrapped in `SinglechildScrollerView` with **Axis.horizontal**, 
the normal situation should be like [this ](https://github.com/asjqkkkk/markdown_widget/issues/20#issuecomment-626732155)

**Closed** 2022-09-15 07:58 UTC
Labels: bug
